### ISSUE TITLE
Settle on a way to handle package.json

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/notifier-server#13]
Ok, this is a fork and I will probably be fetching updates from upstream, but I'd still like to keep my own version system, issue tracking, feature requesting, etc.

I'm gonna need some thoughts from @cristiandouce and probably @alexanderbeletsky, if he can spare some time.

**Comment by alexbeletsky** [comment]
I've checked the scope of your work and it looks interesting. I didn't expect `notifier` could be a project to fork and proceed, but I'll be happy to help to create one.

**Comment by gvilarino** [comment]
Thanks @alexanderbeletsky ! Actually mi intention is to make it a standalone project for other applications to delegate both the notification mechanisms, scheduling and possible transports (mail, in-app, sms, etc.).

My plan is to start using it in the next couple of weeks for [our main app](https://github.com/DemocracyOS/app) but for a lot more stuff in the future.

That being said, I'm not quite sure how the versioning should be handled. Any ideas?

**Comment by alexbeletsky** [comment]
I understand your intention, this something I wanted to create by myself, but instead I got specialized solution that works.

Scheduling, transports it would be not hard to support.

What versioning do you mean?

**Comment by gvilarino** [comment]
With versioning I mean the `version` value in `package.json`. Since you're actively hacking on [/notifier](https://github.com/likeastore/notifier/) this will probably be bumped a lot in the near future. I, as well, will be doing stuff to it and would like to keep track of this with version numbers, without being a nuisance to your progress or updates I'll be pullinf from `upstream`.

**Comment by gvilarino** [comment]
Ok, after having a great call and mind-sync we agreed to, in a near future, produce a generic version of the `notifier` and a npm-distributable client for it, and fork that instead.
