### ISSUE TITLE
Upgrade error messages

### ISSUE THREAD

**Issue by vmariano** [DemocracyOS/notifier-server#21]
From https://github.com/DemocracyOS/app/pull/546

We detect when notifier is configured, but not running. Throws a message like:

`{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}` 

for comunication error. We can improve error messages. (Can be a http errors, instead of string errors)

**Comment by gvilarino** [comment]
This shouldn't be under `notifier` but under `notifier-client`. There: https://github.com/DemocracyOS/notifier-client/issues/9
