### ISSUE TITLE
Windows problems

### ISSUE THREAD

**Issue by fuadhasni** [DemocracyOS/notifier-server#47]
NODE_PATH=. DEBUG=democracyos:notifier-server\* in package.json created problems on windows.

Tried setting NODE_PATH env var. but no luck. had to change all imports to refer to correct directories.

**Comment by mjlescano** [comment]
Yup! `notifier-server` is not intended to be used on Windows, neither on `development`. Please, follow up the instructions on how to use DemocracyOS here: http://docs.democracyos.org/install.html
